max_seq_length: 1000
language: kotlin
dataset_size: "inf"
epochs: 6
per_device_train_batch_size: 32
gradient_accumulation_steps: 16
weight_decay: 0.05
learning_rate: 5e-5
no_lora: True
lora_r: 64
lora_alpha: 16
lora_dropout: 0.2
dataset_name: stojchet/base_prediction_dataset
base_model: deepseek-ai/deepseek-coder-1.3b-base
dataset_ref_field: whole_func_string
