def extract_function_completion(model_output, prompt):
    """
    The models output the prompt completion and then continue generating tokens very often.
    This function extracts the code completion from the model output given the prompt.

    Parameters:
    model_output (str): The output generated by the model.
    prompt (str): The prompt that was given to the model.

    Returns:
    The code completion.
    """
    prompt_end_index = model_output.find(prompt) + len(prompt)

    completion = model_output[prompt_end_index:]

    completion_lines = completion.splitlines()

    # todo: this doesnt remove comments - decide if I want to - see if metrics are only exec based
    code_lines = []
    for line in completion_lines:
        if line == "": continue
        if not line.startswith('\t') and not line.startswith(' '):
            if line == "}":
                code_lines.append(line)
            break
        code_lines.append(line)

    final_completion = "\n".join(code_lines)

    return final_completion

