max_seq_length: 0
language: python
dataset_size: 0
epochs: 0
per_device_train_batch_size: 0
gradient_accumulation_steps: 0
learning_rate: 0
lora_r: 0
lora_alpha: 0
lora_dropout: 0
dataset_name: stojchet/somedataset
base_model: deepseek-ai/deepseek-coder-1.3b-base
