max_seq_length: 1000
language: python
dataset_size: 7500
epochs: 4
per_device_train_batch_size: 2
gradient_accumulation_steps: 64
learning_rate: 5e-5
no_lora: True
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
weight_decay: 0.1
dataset_name: stojchet/dpo-final_base_dataset
base_model: "deepseek-ai/deepseek-coder-1.3b-base"
