max_seq_length: 1000
language: python
dataset_size: 15000
epochs: 5
per_device_train_batch_size: 16
gradient_accumulation_steps: 16
learning_rate: 1e-6
no_lora: True
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
warmup_ratio: 0.1
weight_decay: 0.15
dataset_name: stojchet/kto-final_base_dataset
base_model: deepseek-ai/deepseek-coder-1.3b-base